### PR TITLE
Improve macOS setup

### PR DESCRIPTION
**Pull request by trytuna**
Added a check to let the user know that he's missing wget and how to install it on macOS.

I don't know much about Makefiles maybe there is a better more elegant way to do this. At least it is working.

### CODE REVIEW

**Comment by trytuna** [comment]
We should prefer grabbing the xpack binaries from the actual source rather than ArduPilot. As I was on it I also linked to the latest xpack version. My builds worked file. Maybe someone with Windows and Linux can also check if everything builds fine.

@tridge or @Huibean maybe?

**Comment by tridge** [comment]
thanks!
needs to pass CI, and need to check fw size and operation

**Comment by trytuna** [comment]
Since we are using a newer version of the xpack we get a warning from the linker:

`arm-none-eabi/bin/ld: warning: obj/AM32_VIMDRONES_L431_2.16.elf has a LOAD segment with RWX permissions`

According to this website https://wiki.st.com/stm32mcu/wiki/STM32CubeIDE:STM32CubeIDE_errata_1.16.x#General_issues (search for 169316) this is a vulnerability.

Also I am not sure if windows is going to build after my changes. Need to do a couple of CI tries or someone can assist. I dont have access to x64 windows.

**Comment by trytuna** [comment]
macOS and Linux are working well. I also fixed the linker issue (though I don't know if `(READONLY)` has any impact at runtime?).

As for Windows... I don't get it to work properly. Since "make" does not come with the xpack archive it has to be installed separately. That is not quite the truth because the pipeline already provides make, cp, mkdir, cut, fgrep and so on. As for the local development environment, this should be installed from the developer anyways.

My main problem is that I can't test locally which takes me ages to figure simple things out. Maybe you can look into that @tridge . Feel free to chat with me on Discord.

**Comment by trytuna** [comment]
I've also built all make targets to compare the output sizes.

Additionally I timed the command and observed a huge difference in compile time. That has to do with the arm64 version of the xpack toolkit (I ran it on an Apple Silicon computer).

Compare both files with a diff tool of your choice

[old.txt](https://github.com/user-attachments/files/16517086/old.txt)
[new.txt](https://github.com/user-attachments/files/16517087/new.txt)

**Comment by tridge** [comment]
please PR against main repo now, thanks!

**Pull request closed without merging**
